import express from 'express';
import path from 'path';
import {
  getConsentFormTemplates,
  createConsentFormTemplate,
  updateConsentFormTemplate,
  deleteConsentFormTemplate,
  uploadTemplate,
  getPatientConsentForms,
  uploadPatientConsentForm,
  uploadPatientConsent,
  serveConsentFormFile
} from '../controllers/consentFormController.js';
import { authenticateToken, requireRole } from '../middleware/auth.js';
import { generalLimiter } from '../middleware/rateLimiter.js';
import { validateFilePathMiddleware } from '../utils/ssrfProtection.js';

const router = express.Router();

// Logging middleware
router.use((req, res, next) => {
  console.log(`[Consent Forms] ${req.method} ${req.path}`);
  next();
});

// Get all consent form templates
router.get('/templates',
  generalLimiter,
  authenticateToken,
  requireRole(['superadmin', 'urology_nurse', 'urologist', 'doctor']),
  getConsentFormTemplates
);

// Middleware to allow doctors/nurses to create templates for custom tests (auto-generated or uploaded)
// But restrict general template management to superadmin
const checkTemplateCreationPermission = (req, res, next) => {
  const userRole = req.user?.role;
  const isAutoGenerated = req.body.is_auto_generated === 'true' || 
                          req.body.is_auto_generated === true || 
                          req.body.is_auto_generated === '1';
  const hasFile = !!req.file;
  const procedureName = req.body.procedure_name || '';
  const testName = req.body.test_name || '';
  
  console.log(`[Consent Forms] Template creation permission check:`, {
    userRole,
    isAutoGenerated,
    hasFile,
    procedureName,
    testName,
    body: req.body
  });
  
  // Superadmin can create any template
  if (userRole === 'superadmin') {
    console.log(`[Consent Forms] Superadmin access granted`);
    return next();
  }
  
  // Doctors and nurses can create templates for custom tests (both auto-generated and uploaded)
  // This allows them to create templates when adding custom tests in clinical investigations
  if (userRole === 'urologist' || userRole === 'urology_nurse' || userRole === 'doctor') {
    // Check if this is for a custom test (has procedure_name or test_name)
    const hasCustomTestName = (procedureName && procedureName.trim()) || (testName && testName.trim());
    
    // Standard test names that should be restricted to superadmin
    const standardTests = ['MRI', 'TRUS', 'BIOPSY', 'PSA'];
    const testNameUpper = (procedureName || testName || '').toUpperCase();
    const isStandardTest = standardTests.some(test => testNameUpper.includes(test));
    
    // Allow if it's a custom test (not a standard test name)
    // This allows both auto-generated and file upload for custom tests
    if (hasCustomTestName && !isStandardTest) {
      console.log(`[Consent Forms] Doctor/nurse access granted for custom test template (${procedureName || testName})`);
      return next();
    }
    
    // Allow auto-generated templates for any test (even standard ones, if needed)
    if (isAutoGenerated && !hasFile) {
      console.log(`[Consent Forms] Doctor/nurse access granted for auto-generated template`);
      return next();
    }
  }
  
  // Otherwise, insufficient permissions
  console.log(`[Consent Forms] Access denied for role: ${userRole}, isAutoGenerated: ${isAutoGenerated}, hasFile: ${hasFile}`);
  return res.status(403).json({
    success: false,
    message: 'Insufficient permissions. Only superadmin can create general templates. Doctors and nurses can create templates for custom tests only.'
  });
};

// Create a new consent form template
router.post('/templates',
  generalLimiter,
  authenticateToken,
  uploadTemplate.single('template_file'),
  checkTemplateCreationPermission,
  createConsentFormTemplate
);

// Update a consent form template
router.put('/templates/:templateId',
  generalLimiter,
  authenticateToken,
  requireRole(['superadmin']),
  uploadTemplate.single('template_file'),
  updateConsentFormTemplate
);

// Delete a consent form template
router.delete('/templates/:templateId',
  generalLimiter,
  authenticateToken,
  requireRole(['superadmin']),
  deleteConsentFormTemplate
);

// Patient consent forms routes
// Get patient consent forms
router.get('/patients/:patientId',
  generalLimiter,
  authenticateToken,
  requireRole(['urologist', 'doctor', 'urology_nurse', 'gp', 'superadmin']),
  getPatientConsentForms
);

// Upload patient consent form
router.post('/patients/:patientId',
  generalLimiter,
  authenticateToken,
  requireRole(['urologist', 'doctor', 'urology_nurse', 'superadmin']),
  uploadPatientConsent.single('file'),
  uploadPatientConsentForm
);

// Serve consent form files with authentication
router.get('/files/:filePath(*)',
  generalLimiter,
  authenticateToken,
  requireRole(['urologist', 'doctor', 'urology_nurse', 'gp', 'superadmin']),
  validateFilePathMiddleware('filePath', path.join(process.cwd(), 'uploads')),
  serveConsentFormFile
);

export default router;
