/**
 * Shared utilities for consent form operations
 * Reduces code duplication across modal components
 */

import { consentFormService } from '../services/consentFormService';

/**
 * Print an auto-generated consent form
 * @param {Object} template - The consent form template
 * @param {string} testName - The test/procedure name
 * @param {Object} patient - Patient information
 * @param {Function} onError - Optional error callback
 */
const printAutoGeneratedForm = (template, testName, patient, onError) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    const errorMsg = 'Unable to open print window. Please check your popup blocker settings.';
    if (onError) {
      onError(errorMsg);
    }
    return;
  }

  const name = template.procedure_name || template.test_name || testName;
  const type = template.procedure_name ? 'Procedure' : 'Test';
  const dateOfBirth = patient.dateOfBirth || patient.date_of_birth || '';
  const formattedDOB = dateOfBirth ? new Date(dateOfBirth).toLocaleDateString('en-GB') : '';

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${name} Consent Form</title>
      <style>
        @media print {
          @page { margin: 20mm; }
          body { margin: 0; }
        }
        body {
          font-family: 'Arial', sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px;
          background: white;
        }
        .header {
          text-align: center;
          border-bottom: 3px solid #0d9488;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        h1 {
          color: #0d9488;
          font-size: 28px;
          margin: 0;
          font-weight: 700;
        }
        .subtitle {
          color: #6b7280;
          font-size: 14px;
          margin-top: 5px;
        }
        .section {
          margin-bottom: 30px;
        }
        .patient-info {
          padding: 20px;
          background: #f9fafb;
          border-left: 4px solid #0d9488;
          border-radius: 4px;
        }
        .signature-section {
          margin-top: 40px;
          padding-top: 30px;
          border-top: 2px solid #e5e7eb;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${name} Consent Form</h1>
        <p class="subtitle">${type} Consent Form</p>
      </div>
      
      <div class="section">
        <div class="patient-info">
          <p><strong>Patient Name:</strong> ${patient.name || patient.full_name || 'N/A'}</p>
          <p><strong>Date of Birth:</strong> ${formattedDOB || 'N/A'}</p>
          <p><strong>NHS Number:</strong> ${patient.nhsNumber || patient.nhs_number || 'N/A'}</p>
        </div>
      </div>
      
      <div class="section">
        <p style="color: #374151; line-height: 1.8;">
          I, <strong>${patient.name || patient.full_name || '_________________'}</strong>, 
          hereby give my consent for the ${name} ${type.toLowerCase()}.
        </p>
        <p style="color: #374151; line-height: 1.8; margin-top: 20px;">
          I understand the nature of the procedure/test, its risks, benefits, and alternatives. 
          I have had the opportunity to ask questions and all my questions have been answered to my satisfaction.
        </p>
      </div>
      
      <div class="signature-section">
        <div style="display: flex; justify-content: space-between; gap: 40px;">
          <div>
            <p style="color: #374151; font-size: 14px; margin-bottom: 10px;"><strong>Patient Signature:</strong></p>
            <div style="border-bottom: 2px solid #9ca3af; height: 50px; margin-bottom: 10px;"></div>
            <p style="color: #6b7280; font-size: 12px;">Date: _________________</p>
          </div>
          <div>
            <p style="color: #374151; font-size: 14px; margin-bottom: 10px;"><strong>Doctor/Healthcare Provider Signature:</strong></p>
            <div style="border-bottom: 2px solid #9ca3af; height: 50px; margin-bottom: 10px;"></div>
            <p style="color: #6b7280; font-size: 12px;">Date: _________________</p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
};

/**
 * Setup blob URL cleanup for print window
 * @param {Window} printWindow - The print window
 * @param {string} blobUrl - The blob URL to cleanup
 */
const setupBlobCleanup = (printWindow, blobUrl) => {
  // Clean up blob URL after printing
  const cleanupAfterPrint = setTimeout(() => {
    URL.revokeObjectURL(blobUrl);
  }, 1000);

  // Clean up blob URL if window is closed
  const checkClosed = setInterval(() => {
    if (printWindow.closed) {
      clearTimeout(cleanupAfterPrint);
      URL.revokeObjectURL(blobUrl);
      clearInterval(checkClosed);
    }
  }, 1000);

  return { cleanupAfterPrint, checkClosed };
};

/**
 * Print an uploaded PDF template
 * @param {Object} template - The consent form template
 * @param {string} testName - The test/procedure name
 * @param {Function} onError - Optional error callback
 */
const printUploadedTemplate = async (template, testName, onError) => {
  try {
    if (!template.template_file_path) {
      throw new Error('Template file path is missing');
    }

    // Extract relative path from template_file_path (remove 'uploads/' prefix if present)
    // Handle both Windows (\) and Unix (/) path separators
    let relativePath = template.template_file_path.replace(/\\/g, '/');
    
    // Remove 'uploads/' or 'uploads\' prefix if present
    if (relativePath.startsWith('uploads/') || relativePath.startsWith('uploads\\')) {
      relativePath = relativePath.replace(/^uploads[/\\]/, '');
    }

    // Ensure we have a valid path
    if (!relativePath || relativePath.trim() === '') {
      throw new Error('Invalid template file path');
    }

    console.log('Printing uploaded template:', { 
      originalPath: template.template_file_path, 
      relativePath, 
      template_file_url: template.template_file_url,
      is_auto_generated: template.is_auto_generated
    });

    // Fetch the file as blob using authenticated API
    // Note: getConsentFormFile will handle URL encoding, so pass the raw relative path
    const response = await consentFormService.getConsentFormFile(relativePath);
    
    if (!response.success) {
      console.error('Failed to fetch template file:', {
        error: response.error,
        path: relativePath,
        originalPath: template.template_file_path
      });
      throw new Error(response.error || 'Failed to fetch template file');
    }

    // Create blob URL and open for printing
    const blob = response.data;
    const blobUrl = URL.createObjectURL(blob);
    
    const printWindow = window.open(blobUrl, '_blank');
    if (!printWindow) {
      URL.revokeObjectURL(blobUrl);
      const errorMsg = 'Unable to open the template file. Please check your popup blocker settings.';
      if (onError) {
        onError(errorMsg);
      }
      return;
    }

    // Setup cleanup handlers
    printWindow.onload = () => {
      setTimeout(() => {
        try {
          printWindow.print();
          setTimeout(() => URL.revokeObjectURL(blobUrl), 1000);
        } catch (printError) {
          console.error('Error triggering print:', printError);
          URL.revokeObjectURL(blobUrl);
        }
      }, 500);
    };

    setupBlobCleanup(printWindow, blobUrl);
  } catch (fetchError) {
    console.error('Error fetching template file for printing:', fetchError);
    const errorMsg = `Unable to load the template file for ${testName}. ${fetchError.message || 'The file may have been moved or deleted. Please contact the administrator.'}`;
    if (onError) {
      onError(errorMsg);
    }
  }
};

/**
 * Generate HTML content for auto-generated consent form
 * @param {string} name - Form name
 * @param {string} type - Form type (Procedure or Test)
 * @param {Object} patient - Patient information
 * @param {string} formattedDOB - Formatted date of birth
 * @returns {string} HTML content
 */
const generateAutoGeneratedFormHTML = (name, type, patient, formattedDOB) => {
  const patientName = patient.name || patient.full_name || 'N/A';
  const nhsNumber = patient.nhsNumber || patient.nhs_number || 'N/A';
  const typeLower = type.toLowerCase();

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${name} Consent Form</title>
      <style>
        @media print {
          @page { margin: 20mm; }
          body { margin: 0; }
        }
        body {
          font-family: 'Arial', sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px;
          background: white;
        }
        .header {
          text-align: center;
          border-bottom: 3px solid #0d9488;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        h1 {
          color: #0d9488;
          font-size: 28px;
          margin: 0;
          font-weight: 700;
        }
        .subtitle {
          color: #6b7280;
          font-size: 14px;
          margin-top: 5px;
        }
        .section {
          margin-bottom: 30px;
        }
        .patient-info {
          padding: 20px;
          background: #f9fafb;
          border-left: 4px solid #0d9488;
          border-radius: 4px;
        }
        .signature-section {
          margin-top: 40px;
          padding-top: 30px;
          border-top: 2px solid #e5e7eb;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${name} Consent Form</h1>
        <p class="subtitle">${type} Consent Form</p>
      </div>
      
      <div class="section">
        <div class="patient-info">
          <p><strong>Patient Name:</strong> ${patientName}</p>
          <p><strong>Date of Birth:</strong> ${formattedDOB || 'N/A'}</p>
          <p><strong>NHS Number:</strong> ${nhsNumber}</p>
        </div>
      </div>
      
      <div class="section">
        <p style="color: #374151; line-height: 1.8;">
          I, <strong>${patientName}</strong>, 
          hereby give my consent for the ${name} ${typeLower}.
        </p>
        <p style="color: #374151; line-height: 1.8; margin-top: 20px;">
          I understand the nature of the procedure/test, its risks, benefits, and alternatives. 
          I have had the opportunity to ask questions and all my questions have been answered to my satisfaction.
        </p>
      </div>
      
      <div class="signature-section">
        <div style="display: flex; justify-content: space-between; gap: 40px;">
          <div>
            <p style="color: #374151; font-size: 14px; margin-bottom: 10px;"><strong>Patient Signature:</strong></p>
            <div style="border-bottom: 2px solid #9ca3af; height: 50px; margin-bottom: 10px;"></div>
            <p style="color: #6b7280; font-size: 12px;">Date: _________________</p>
          </div>
          <div>
            <p style="color: #374151; font-size: 14px; margin-bottom: 10px;"><strong>Doctor/Healthcare Provider Signature:</strong></p>
            <div style="border-bottom: 2px solid #9ca3af; height: 50px; margin-bottom: 10px;"></div>
            <p style="color: #6b7280; font-size: 12px;">Date: _________________</p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `;
};

/**
 * Get blob URL for auto-generated consent form
 * @param {Object} template - The consent form template
 * @param {string} testName - The test/procedure name
 * @param {Object} patient - Patient information
 * @returns {{success: boolean, blobUrl?: string, fileName?: string, error?: string}}
 */
const getAutoGeneratedFormBlobUrl = (template, testName, patient) => {
  const name = template.procedure_name || template.test_name || testName;
  const type = template.procedure_name ? 'Procedure' : 'Test';
  const dateOfBirth = patient.dateOfBirth || patient.date_of_birth || '';
  const formattedDOB = dateOfBirth ? new Date(dateOfBirth).toLocaleDateString('en-GB') : '';

  const htmlContent = generateAutoGeneratedFormHTML(name, type, patient, formattedDOB);
  const blob = new Blob([htmlContent], { type: 'text/html' });
  const blobUrl = URL.createObjectURL(blob);
  const fileName = `${name} Consent Form.html`;

  return { success: true, blobUrl, fileName };
};

/**
 * Get blob URL for uploaded PDF template
 * @param {Object} template - The consent form template
 * @param {string} testName - The test/procedure name
 * @returns {Promise<{success: boolean, blobUrl?: string, fileName?: string, error?: string}>}
 */
const getUploadedTemplateBlobUrl = async (template, testName) => {
  let relativePath = template.template_file_path.replace(/\\/g, '/');
  
  if (relativePath.startsWith('uploads/') || relativePath.startsWith('uploads\\')) {
    relativePath = relativePath.replace(/^uploads[/\\]/, '');
  }

  if (!relativePath || relativePath.trim() === '') {
    return { 
      success: false, 
      error: 'The template file path is invalid. Please contact the administrator to re-upload the template.' 
    };
  }

  // Try fetching via the service first
  const response = await consentFormService.getConsentFormFile(relativePath);
  
  if (response.success) {
    const blob = response.data;
    const blobUrl = URL.createObjectURL(blob);
    const fileName = template.template_file_path.split('/').pop() || 
                     template.template_file_path.split('\\').pop() || 
                     `${testName} Consent Form.pdf`;
    return { success: true, blobUrl, fileName };
  }

  // If file service fails, try using template_file_url as fallback
  // Extract the path from the full URL and try via the service again
  if (template.template_file_url) {
    try {
      console.log('File service failed, trying to extract path from template_file_url:', template.template_file_url);
      
      // Extract the path from the URL (e.g., /api/consent-forms/files/consent-forms%2Ftemplates%2Ffile.pdf)
      const urlObj = new URL(template.template_file_url);
      const pathMatch = urlObj.pathname.match(/\/files\/(.+)$/);
      
      if (pathMatch) {
        // Decode the path to get the original relative path
        const decodedPath = decodeURIComponent(pathMatch[1]);
        console.log('Extracted path from URL, retrying:', decodedPath);
        
        // Try fetching again with the extracted path
        const retryResponse = await consentFormService.getConsentFormFile(decodedPath);
        
        if (retryResponse.success) {
          const blob = retryResponse.data;
          const blobUrl = URL.createObjectURL(blob);
          const fileName = template.template_file_name || 
                           template.template_file_path?.split('/').pop() || 
                           template.template_file_path?.split('\\').pop() || 
                           `${testName} Consent Form.pdf`;
          return { success: true, blobUrl, fileName };
        }
      }
    } catch (urlError) {
      console.error('Error extracting path from template_file_url:', urlError);
      // Continue to return the original error
    }
  }

  // Return user-friendly error message (no technical details)
  return { 
    success: false, 
    error: 'The consent form template file could not be found. The file may have been moved or deleted. Please contact the administrator to re-upload the template.' 
  };
};

/**
 * Get consent form blob URL for modal viewing (handles both auto-generated and uploaded templates)
 * @param {Object} template - The consent form template
 * @param {string} testName - The test/procedure name
 * @param {Object} patient - Patient information
 * @returns {Promise<{success: boolean, blobUrl?: string, fileName?: string, error?: string}>}
 */
export const getConsentFormBlobUrl = async (template, testName, patient) => {
  if (!template || !patient) {
    return { success: false, error: 'Missing template or patient' };
  }

  try {
    if (template.is_auto_generated) {
      return getAutoGeneratedFormBlobUrl(template, testName, patient);
    }
    
    if (template.template_file_path && template.template_file_path.trim() !== '') {
      return await getUploadedTemplateBlobUrl(template, testName);
    }
    
    return { 
      success: false, 
      error: `No template file is available for ${testName}. Please ensure the template has been uploaded in the superadmin panel.` 
    };
  } catch (error) {
    console.error('Error getting consent form blob URL:', error);
    return { 
      success: false, 
      error: `Unable to load the consent form for ${testName}. Please try again or contact support if the problem persists.` 
    };
  }
};

/**
 * Print consent form (handles both auto-generated and uploaded templates)
 * @param {Object} template - The consent form template
 * @param {string} testName - The test/procedure name
 * @param {Object} patient - Patient information
 * @param {Function} onError - Optional error callback for uploaded templates
 */
export const printConsentForm = async (template, testName, patient, onError) => {
  if (!template || !patient) {
    console.warn('printConsentForm: Missing template or patient', { template, patient });
    return;
  }

  try {
    if (template.is_auto_generated) {
      printAutoGeneratedForm(template, testName, patient, onError);
    } else if (template.template_file_path && template.template_file_path.trim() !== '') {
      // For uploaded templates, we only need template_file_path
      // template_file_url is optional (we can construct it if needed)
      await printUploadedTemplate(template, testName, onError);
    } else {
      // No file path available
      const errorMsg = `No template file available for ${testName}. Please ensure the template has been uploaded in the superadmin panel.`;
      console.error('printConsentForm: No template file path', { 
        template: {
          id: template.id,
          name: template.procedure_name || template.test_name,
          is_auto_generated: template.is_auto_generated,
          template_file_path: template.template_file_path,
          template_file_url: template.template_file_url
        }, 
        testName 
      });
      if (onError) {
        onError(errorMsg);
      }
    }
  } catch (error) {
    console.error('Error printing consent form:', error);
    const errorMsg = `Failed to print consent form for ${testName}. ${error.message || 'Please try again.'}`;
    if (onError) {
      onError(errorMsg);
    }
  }
};

