import React, { useState, useEffect } from 'react';
import {
  X,
  FileText,
  Upload,
  Sparkles,
  CheckCircle,
  Loader2,
  FileCheck,
  AlertCircle
} from 'lucide-react';
import { consentFormService } from '../../services/consentFormService';

const AddConsentFormModal = ({ isOpen, onClose, onSuccess, template = null }) => {
  const [formData, setFormData] = useState({
    procedure_name: '',
    test_name: '',
    type: 'procedure', // 'procedure' or 'test'
    is_auto_generated: false,
    template_file: null
  });
  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [uploadedFile, setUploadedFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [autoGeneratedPreview, setAutoGeneratedPreview] = useState(null);

  // Reset form when modal opens/closes or template changes
  useEffect(() => {
    if (isOpen) {
      if (template) {
        // Edit mode
        setFormData({
          procedure_name: template.procedure_name || '',
          test_name: template.test_name || '',
          type: template.procedure_name ? 'procedure' : 'test',
          is_auto_generated: template.is_auto_generated || false,
          template_file: null
        });
        setUploadedFile(null);
        setPreviewUrl(template.template_file_url || null);
      } else {
        // Add mode
        setFormData({
          procedure_name: '',
          test_name: '',
          type: 'procedure',
          is_auto_generated: false,
          template_file: null
        });
        setUploadedFile(null);
        setPreviewUrl(null);
      }
      setErrors({});
      setAutoGeneratedPreview(null);
    }
  }, [isOpen, template]);

  // Generate auto-generated preview when auto-generate is checked
  useEffect(() => {
    if (formData.is_auto_generated && (formData.procedure_name || formData.test_name)) {
      generateAutoPreview();
    } else {
      setAutoGeneratedPreview(null);
    }
  }, [formData.is_auto_generated, formData.procedure_name, formData.test_name]);

  const generateAutoPreview = () => {
    const name = formData.procedure_name || formData.test_name;
    const type = formData.type === 'procedure' ? 'Procedure' : 'Test';
    
    // Generate a beautiful consent form HTML preview
    const previewHTML = `
      <div style="font-family: 'Arial', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; background: white; box-shadow: 0 0 20px rgba(0,0,0,0.1);">
        <div style="text-align: center; border-bottom: 3px solid #0d9488; padding-bottom: 20px; margin-bottom: 30px;">
          <h1 style="color: #0d9488; font-size: 28px; margin: 0; font-weight: 700;">CONSENT FORM</h1>
          <p style="color: #6b7280; font-size: 14px; margin-top: 5px;">${type} Consent</p>
        </div>
        
        <div style="margin-bottom: 30px;">
          <h2 style="color: #1f2937; font-size: 20px; margin-bottom: 15px; font-weight: 600;">${name.toUpperCase()}</h2>
          <p style="color: #4b5563; line-height: 1.6; font-size: 14px;">
            I hereby give my consent for the ${formData.type === 'procedure' ? 'procedure' : 'test'} mentioned above to be performed on me.
          </p>
        </div>

        <div style="margin-bottom: 30px; padding: 20px; background: #f9fafb; border-left: 4px solid #0d9488; border-radius: 4px;">
          <h3 style="color: #1f2937; font-size: 16px; margin-bottom: 15px; font-weight: 600;">Patient Information</h3>
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 15px; font-size: 14px;">
            <div>
              <strong style="color: #374151;">Patient Name:</strong>
              <p style="color: #6b7280; margin-top: 5px;">_________________________</p>
            </div>
            <div>
              <strong style="color: #374151;">Date of Birth:</strong>
              <p style="color: #6b7280; margin-top: 5px;">_________________________</p>
            </div>
            <div>
              <strong style="color: #374151;">Hospital Number:</strong>
              <p style="color: #6b7280; margin-top: 5px;">_________________________</p>
            </div>
            <div>
              <strong style="color: #374151;">Date:</strong>
              <p style="color: #6b7280; margin-top: 5px;">_________________________</p>
            </div>
          </div>
        </div>

        <div style="margin-bottom: 30px;">
          <h3 style="color: #1f2937; font-size: 16px; margin-bottom: 15px; font-weight: 600;">Procedure/Test Details</h3>
          <p style="color: #4b5563; line-height: 1.8; font-size: 14px; margin-bottom: 15px;">
            I understand that the ${formData.type === 'procedure' ? 'procedure' : 'test'} involves:
          </p>
          <ul style="color: #4b5563; line-height: 1.8; font-size: 14px; padding-left: 20px;">
            <li>Explanation of the ${formData.type === 'procedure' ? 'procedure' : 'test'} has been provided to me</li>
            <li>I have been informed about the benefits and potential risks</li>
            <li>I have had the opportunity to ask questions</li>
            <li>I understand that I can withdraw my consent at any time</li>
          </ul>
        </div>

        <div style="margin-bottom: 30px; padding: 20px; background: #fef3c7; border: 1px solid #fbbf24; border-radius: 4px;">
          <h3 style="color: #92400e; font-size: 16px; margin-bottom: 10px; font-weight: 600;">Important Notes</h3>
          <p style="color: #78350f; line-height: 1.6; font-size: 13px; margin: 0;">
            Please read this form carefully. If you have any questions or concerns, please discuss them with your healthcare provider before signing.
          </p>
        </div>

        <div style="margin-top: 40px; padding-top: 30px; border-top: 2px solid #e5e7eb;">
          <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-bottom: 30px;">
            <div>
              <p style="color: #374151; font-size: 14px; margin-bottom: 10px;"><strong>Patient Signature:</strong></p>
              <div style="border-bottom: 2px solid #9ca3af; height: 50px; margin-bottom: 10px;"></div>
              <p style="color: #6b7280; font-size: 12px;">Date: _________________</p>
            </div>
            <div>
              <p style="color: #374151; font-size: 14px; margin-bottom: 10px;"><strong>Witness Signature:</strong></p>
              <div style="border-bottom: 2px solid #9ca3af; height: 50px; margin-bottom: 10px;"></div>
              <p style="color: #6b7280; font-size: 12px;">Date: _________________</p>
            </div>
          </div>
          <div>
            <p style="color: #374151; font-size: 14px; margin-bottom: 10px;"><strong>Doctor/Healthcare Provider Signature:</strong></p>
            <div style="border-bottom: 2px solid #9ca3af; height: 50px; margin-bottom: 10px;"></div>
            <p style="color: #6b7280; font-size: 12px;">Date: _________________</p>
          </div>
        </div>

        <div style="margin-top: 30px; padding: 15px; background: #f3f4f6; border-radius: 4px; text-align: center;">
          <p style="color: #6b7280; font-size: 12px; margin: 0;">
            This is an auto-generated consent form template. It will be customized for each patient.
          </p>
        </div>
      </div>
    `;
    
    setAutoGeneratedPreview(previewHTML);
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
    
    // Clear errors when user starts typing
    if (errors[name]) {
      setErrors(prev => ({
        ...prev,
        [name]: ''
      }));
    }
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      // Validate file type
      const allowedTypes = ['application/pdf'];
      if (!allowedTypes.includes(file.type)) {
        setErrors(prev => ({
          ...prev,
          template_file: 'Please select a PDF file'
        }));
        return;
      }
      
      // Validate file size (10MB limit)
      if (file.size > 10 * 1024 * 1024) {
        setErrors(prev => ({
          ...prev,
          template_file: 'File size must be less than 10MB'
        }));
        return;
      }
      
      setUploadedFile(file);
      setFormData(prev => ({
        ...prev,
        template_file: file
      }));
      
      // Create preview URL
      const url = URL.createObjectURL(file);
      setPreviewUrl(url);
      
      setErrors(prev => ({
        ...prev,
        template_file: ''
      }));
    }
  };

  const handleRemoveFile = () => {
    setUploadedFile(null);
    setFormData(prev => ({
      ...prev,
      template_file: null
    }));
    if (previewUrl) {
      URL.revokeObjectURL(previewUrl);
      setPreviewUrl(null);
    }
  };

  const validateForm = () => {
    const newErrors = {};
    
    if (formData.type === 'procedure' && !formData.procedure_name.trim()) {
      newErrors.procedure_name = 'Procedure name is required';
    }
    
    if (formData.type === 'test' && !formData.test_name.trim()) {
      newErrors.test_name = 'Test name is required';
    }
    
    if (!formData.is_auto_generated && !formData.template_file && !template) {
      newErrors.template_file = 'Please upload a PDF template or enable auto-generation';
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!validateForm()) {
      return;
    }
    
    setIsSubmitting(true);
    
    try {
      let response;
      
      if (template) {
        // Update existing template
        response = await consentFormService.updateConsentFormTemplate(template.id, formData);
      } else {
        // Create new template
        response = await consentFormService.createConsentFormTemplate(formData);
      }
      
      if (response.success) {
        onSuccess();
      } else {
        setErrors({
          submit: response.error || 'Failed to save template'
        });
      }
    } catch (error) {
      console.error('Error saving template:', error);
      setErrors({
        submit: error?.response?.data?.message || 'Failed to save template'
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-sm flex items-center justify-center z-50 p-4 overflow-y-auto">
      <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full my-8">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-gradient-to-r from-teal-600 to-teal-700 rounded-lg flex items-center justify-center">
              <FileText className="h-5 w-5 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-semibold text-gray-900">
                {template ? 'Edit Consent Form Template' : 'Add Consent Form Template'}
              </h2>
              <p className="text-sm text-gray-500 mt-1">
                {template ? 'Update the consent form template' : 'Create a new consent form template for procedures or tests'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X className="h-6 w-6" />
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="p-6">
          <div className="space-y-6">
            {/* Type Selection */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Template Type *
              </label>
              <div className="flex space-x-4">
                <label className="flex items-center">
                  <input
                    type="radio"
                    name="type"
                    value="procedure"
                    checked={formData.type === 'procedure'}
                    onChange={handleInputChange}
                    className="h-4 w-4 text-teal-600 focus:ring-teal-500 border-gray-300"
                  />
                  <span className="ml-2 text-sm text-gray-700">Procedure</span>
                </label>
                <label className="flex items-center">
                  <input
                    type="radio"
                    name="type"
                    value="test"
                    checked={formData.type === 'test'}
                    onChange={handleInputChange}
                    className="h-4 w-4 text-teal-600 focus:ring-teal-500 border-gray-300"
                  />
                  <span className="ml-2 text-sm text-gray-700">Test</span>
                </label>
              </div>
            </div>

            {/* Procedure/Test Name */}
            {formData.type === 'procedure' ? (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Procedure Name *
                </label>
                <select
                  name="procedure_name"
                  value={formData.procedure_name}
                  onChange={handleInputChange}
                  className={`block w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 ${
                    errors.procedure_name ? 'border-red-300' : 'border-gray-300'
                  }`}
                >
                  <option value="">Select a procedure...</option>
                  <option value="MRI">MRI</option>
                  <option value="TRUS">TRUS</option>
                  <option value="Biopsy">Biopsy</option>
                </select>
                {errors.procedure_name && (
                  <p className="mt-1 text-sm text-red-600 flex items-center">
                    <AlertCircle className="h-4 w-4 mr-1" />
                    {errors.procedure_name}
                  </p>
                )}
              </div>
            ) : (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Test Name *
                </label>
                <select
                  name="test_name"
                  value={formData.test_name}
                  onChange={handleInputChange}
                  className={`block w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-teal-500 ${
                    errors.test_name ? 'border-red-300' : 'border-gray-300'
                  }`}
                >
                  <option value="">Select a test...</option>
                  <option value="MRI">MRI</option>
                  <option value="TRUS">TRUS</option>
                  <option value="Biopsy">Biopsy</option>
                </select>
                {errors.test_name && (
                  <p className="mt-1 text-sm text-red-600 flex items-center">
                    <AlertCircle className="h-4 w-4 mr-1" />
                    {errors.test_name}
                  </p>
                )}
              </div>
            )}

            {/* Auto-Generate Checkbox */}
            <div className="flex items-start">
              <div className="flex items-center h-5">
                <input
                  type="checkbox"
                  name="is_auto_generated"
                  checked={formData.is_auto_generated}
                  onChange={handleInputChange}
                  className="h-4 w-4 text-teal-600 focus:ring-teal-500 border-gray-300 rounded"
                />
              </div>
              <div className="ml-3 text-sm">
                <label className="font-medium text-gray-700 flex items-center">
                  <Sparkles className="h-4 w-4 mr-2 text-purple-600" />
                  Auto-Generate Consent Form
                </label>
                <p className="text-gray-500 mt-1">
                  Automatically generate a beautiful consent form template. If unchecked, you can upload a custom PDF template.
                </p>
              </div>
            </div>

            {/* Auto-Generated Preview */}
            {formData.is_auto_generated && autoGeneratedPreview && (
              <div className="border border-purple-200 rounded-lg p-4 bg-purple-50">
                <div className="flex items-center mb-3">
                  <Sparkles className="h-5 w-5 text-purple-600 mr-2" />
                  <h3 className="text-sm font-semibold text-purple-900">Auto-Generated Preview</h3>
                </div>
                <div 
                  className="bg-white rounded border border-purple-200 p-4 max-h-96 overflow-y-auto"
                  dangerouslySetInnerHTML={{ __html: autoGeneratedPreview }}
                />
              </div>
            )}

            {/* PDF Upload Section */}
            {!formData.is_auto_generated && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Upload PDF Template *
                </label>
                {!uploadedFile && !previewUrl ? (
                  <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-lg hover:border-teal-400 transition-colors">
                    <div className="space-y-1 text-center">
                      <Upload className="mx-auto h-12 w-12 text-gray-400" />
                      <div className="flex text-sm text-gray-600">
                        <label className="relative cursor-pointer bg-white rounded-md font-medium text-teal-600 hover:text-teal-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-teal-500">
                          <span>Upload a PDF file</span>
                          <input
                            type="file"
                            accept=".pdf"
                            onChange={handleFileChange}
                            className="sr-only"
                          />
                        </label>
                        <p className="pl-1">or drag and drop</p>
                      </div>
                      <p className="text-xs text-gray-500">PDF up to 10MB</p>
                    </div>
                  </div>
                ) : (
                  <div className="mt-1 border border-gray-300 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center space-x-3">
                        <FileCheck className="h-8 w-8 text-teal-600" />
                        <div>
                          <p className="text-sm font-medium text-gray-900">
                            {uploadedFile?.name || 'Template file'}
                          </p>
                          <p className="text-xs text-gray-500">
                            {uploadedFile ? `${(uploadedFile.size / 1024).toFixed(2)} KB` : 'Existing file'}
                          </p>
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={handleRemoveFile}
                        className="text-red-600 hover:text-red-800 text-sm font-medium"
                      >
                        Remove
                      </button>
                    </div>
                    {previewUrl && (
                      <div className="mt-3">
                        <iframe
                          src={previewUrl}
                          className="w-full h-64 border border-gray-300 rounded"
                          title="PDF Preview"
                        />
                        <p className="mt-2 text-xs text-gray-500">
                          Note: PDF editing capabilities can be added using libraries like pdf-lib or react-pdf. 
                          For now, you can upload a PDF template that will be used as-is.
                        </p>
                      </div>
                    )}
                  </div>
                )}
                {errors.template_file && (
                  <p className="mt-1 text-sm text-red-600 flex items-center">
                    <AlertCircle className="h-4 w-4 mr-1" />
                    {errors.template_file}
                  </p>
                )}
              </div>
            )}

            {/* Submit Error */}
            {errors.submit && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                <p className="text-sm text-red-600 flex items-center">
                  <AlertCircle className="h-4 w-4 mr-2" />
                  {errors.submit}
                </p>
              </div>
            )}

            {/* Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 border border-gray-300 text-gray-700 font-medium rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-colors"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-4 py-2 bg-gradient-to-r from-teal-600 to-teal-700 text-white font-medium rounded-lg hover:opacity-90 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-offset-2 transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Saving...
                  </>
                ) : (
                  <>
                    <CheckCircle className="h-4 w-4 mr-2" />
                    {template ? 'Update Template' : 'Create Template'}
                  </>
                )}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddConsentFormModal;

